from django.utils import translation
translation.activate('en')



def get_validation_rules(type_id, region_id, town_id=None):    
    return {
    '1': {
        '1': [
            {'label': 'rooms', 'type': 'integer', "title": "Количество комнат", "placeholder": "Количество комнат", "required": True, 'input': False},
            {'label': 'building_id', 'type': 'integer', "title": "Жилой комплекс*", "placeholder": "Жилой комплекс", "required": False, 'input': False},
            {'label': 'serie', 'type': 'integer', "title": "Серия", "placeholder": "Выберите серию", "required": True, 'input': False},
            {'label': 'building_type', 'type': 'integer', "title": "Тип строения", "placeholder": "Тип строения", "required": True, 'input': False},
            {'label': 'year', 'type': 'integer', "title": "Год постройки (сдачи в эксплуатацию)", "placeholder": "", "required": False, 'input': True},
            {'label': 'floor', 'type': 'integer', "title": "Этаж", "placeholder": "Этаж", "required": True, 'input': False},
            {'label': 'floors', 'type': 'integer', "title": "", "placeholder": "Всего этажей", "required": True, 'input': False},
            {'label': 'land_square', 'type': 'integer', "title": "Площадь дома м2*", "placeholder": "", "required": True, 'input': True}, 
            {'label': 'living_square', 'type': 'integer', "title": "жилая", "placeholder": "", "required": False, 'input': True},
            {'label': 'kitchen_square', 'type': 'integer', "title": "кухня", "placeholder": "", "required": False, 'input': True},
            {'label': 'square', 'type': 'integer', "title": "Площадь участка, соток*", "placeholder": "", "required": True, 'input': True},
            {'label': 'condition', 'type': 'integer', "title": "Состояние*", "placeholder": "Состояние", "required": True, 'input': False}, 
            {'label': 'heating', 'type': 'integer',  "title": "Отопление*", "placeholder": "Отопление", "required": False, 'input': False},
            {'label': 'balkony', 'type': 'integer', "title": "Балкон", "placeholder": "", "required": False, 'input': False}, 
            {'label': 'door', 'type': 'integer',  "title": "Входная дверь", "placeholder": "", "required": False, 'input': False},
            {'label': 'parking', 'type': 'integer',  "title": "Парковка", "placeholder": "", "required": False, 'input': False},
            {'label': 'phone_info', 'type': 'integer', "title": "Телефон", "placeholder": "", 'required': False, "input": False},
            {'label': 'internet', 'type': 'integer', "title": "Интернет", "placeholder": "", 'required': False, "input": False},
            {'label': 'toilet', 'type': 'integer', "title": "Санузел", "placeholder": "", 'required': False, "input": False},
            {'label': 'canalization', 'type': 'integer', "title": "Канализация", "placeholder": "", 'required': False, "input": False},
            {'label': 'gas', 'type': 'integer', "title": "Газ", "placeholder": "", 'required': False, "input": False},
            {'label': 'water', 'type': 'integer', "title": "Питьевая вода", "placeholder": "", 'required': False, "input": False},
            {'label': 'furniture', 'type': 'integer', "title": "Мебель", "placeholder": "", 'required': False, "input": False},
            {'label': 'flooring', 'type': 'integer', "title": "Пол", "placeholder": "", 'required': False, "input": False},
            {'label': 'ceiling_height', 'type': 'float', "title": "Высота потолков", "placeholder": "", 'required': False, "input": True},
            {'label': 'safety', 'type': 'integer', "title": "Безопасность", "placeholder": "", 'required': False, "input": False},
            {'label': 'flat_options', 'type': 'integer', "title": "Разное", "placeholder": "",  'required': False, "input": False},
            {'label': 'documents', 'type': 'integer', "title": "Правоустанавливающие документы", "placeholder": "", 'required': True, "input": False},
            {'label': 'description', 'type': 'string', "title": "Описание", "placeholder": "Опишите, почему ваш объект стоит выбрать...", 'required': True, "input": True},
        ],
        '2': [
            {'label': 'rooms', 'type': 'integer', "title": "Количество комнат", "placeholder": "Количество комнат*", "required": True, 'input': False},
            {'label': 'material', 'type': 'integer', "title": "Тип строения*", "placeholder": "Тип строения", "required": True, 'input': False},
            {'label': 'floor', 'type': 'integer', "title": "Кол-во этажей", "placeholder": "Всего этажей", "required": False, 'input': False},
            {'label': 'year', 'type': 'integer', "title": "Год постройки (сдачи в эксплуатацию)", "placeholder": "", "required": False, 'input': True},
            {'label': 'land_square', 'type': 'integer', "title": "Площадь дома м2*", "placeholder": "", "required": True, 'input': True}, 
            {'label': 'living_square', 'type': 'integer', "title": "жилая", "placeholder": "", "required": False, 'input': True},
            {'label': 'kitchen_square', 'type': 'integer', "title": "кухня", "placeholder": "", "required": False, 'input': True},
            {'label': 'square', 'type': 'integer', "title": "Площадь участка, соток*", "placeholder": "", "required": True, 'input': True},
            {'label': 'condition', 'type': 'integer', "title": "Состояние*", "placeholder": "Состояние", "required": True, 'input': False}, 
            {'label': 'heating', 'type': 'integer',  "title": "Отопление*", "placeholder": "Отопление", "required": False, 'input': False},
            {'label': 'phone_info', 'type': 'integer', "title": "Телефон", "placeholder": "", 'required': False, "input": False},
            {'label': 'internet', 'type': 'integer', "title": "Интернет", "placeholder": "", 'required': False, "input": False},
            {'label': 'toilet', 'type': 'integer', "title": "Санузел", "placeholder": "", 'required': False, "input": False},
            {'label': 'canalization', 'type': 'integer', "title": "Канализация", "placeholder": "", 'required': False, "input": False},
            {'label': 'gas', 'type': 'integer', "title": "Газ", "placeholder": "", 'required': False, "input": False},
            {'label': 'water', 'type': 'integer', "title": "Питьевая вода", "placeholder": "", 'required': False, "input": False},
            {'label': 'furniture', 'type': 'integer', "title": "Мебель", "placeholder": "", 'required': False, "input": False},
            {'label': 'flooring', 'type': 'integer', "title": "Пол", "placeholder": "", 'required': False, "input": False},
            {'label': 'ceiling_height', 'type': 'float', "title": "Высота потолков", "placeholder": "", 'required': False, "input": True},
            # для  Безопасность Разное итд фронту нужно отправить запрос на public/data потом оттуда получить id значений(решетки на окнах) и отправить запрос 1, 8, 3,
            {'label': 'safety', 'type': 'integer', "title": "Безопасность", "placeholder": "", 'required': False, "input": False},
            {'label': 'flat_options', 'type': 'integer', "title": "Разное", "placeholder": "",  'required': False, "input": False},
            {'label': 'documents', 'type': 'integer', "title": "Правоустанавливающие документы", "placeholder": "", 'required': True, "input": False},
            {'label': 'description', 'type': 'string', "title": "Описание", "placeholder": "Опишите, почему ваш объект стоит выбрать...", 'required': True, "input": True},
        ],
        '3': [
            {'label': 'commercial_type', 'type': 'integer', "title": "Тип объекта", "placeholder": "Тип объекта", "required": True, 'input': False},
            {'label': 'building_id', 'type': 'integer', "title": "Жилой комплекс*", "placeholder": "Жилой комплекс", "required": False, 'input': False},
            {'label': 'year', 'type': 'integer', "title": "Год постройки (сдачи в эксплуатацию)", "placeholder": "", "required": False, 'input': True},
            {'label': 'material', 'type': 'integer', "title": "Тип строения*", "placeholder": "Тип строения", "required": False, 'input': False},
            {'label': 'floor', 'type': 'integer', "title": "Этаж", "placeholder": "Этаж", "required": False, 'input': False},
            {'label': 'floors', 'type': 'integer', "title": "", "placeholder": "Всего этажей", "required": False, 'input': False},
            {'label': 'land_square', 'type': 'integer', "title": "Площадь дома м2*", "placeholder": "", "required": True, 'input': True}, 
            {'label': 'square', 'type': 'integer', "title": "Площадь участка, соток*", "placeholder": "", "required": False, 'input': True},
            {'label': 'condition', 'type': 'integer', "title": "Состояние*", "placeholder": "Состояние", "required": True, 'input': False}, 
            {'label': 'heating', 'type': 'integer',  "title": "Отопление*", "placeholder": "Отопление", "required": False, 'input': False},
            {'label': 'phone_info', 'type': 'integer', "title": "Телефон", "placeholder": "", 'required': False, "input": False},
            {'label': 'internet', 'type': 'integer', "title": "Интернет", "placeholder": "", 'required': False, "input": False},
            {'label': 'ceiling_height', 'type': 'float', "title": "Высота потолков", "placeholder": "", 'required': False, "input": True},
            {'label': 'safety', 'type': 'integer', "title": "Безопасность", "placeholder": "", 'required': False, "input": False},
            {'label': 'documents', 'type': 'integer', "title": "Правоустанавливающие документы", "placeholder": "", 'required': True, "input": False},
            {'label': 'description', 'type': 'string', "title": "Описание", "placeholder": "Опишите, почему ваш объект стоит выбрать...", 'required': True, "input": True},
        ],
        '4': [
            {'label': 'rooms', 'type': 'integer', "title": "Количество комнат", "placeholder": "Количество комнат*", "required": True, 'input': False},
            {'label': 'room_location', 'type': 'integer', "title": "Расположение", "placeholder": "Расположение", "required": True, 'input': False},
            {'label': 'year', 'type': 'integer', "title": "Год постройки (сдачи в эксплуатацию)", "placeholder": "", "required": False, 'input': True},
            {'label': 'floor', 'type': 'integer', "title": "Этаж", "placeholder": "Этаж", "required": False, 'input': False},
            {'label': 'floors', 'type': 'integer', "title": "", "placeholder": "Всего этажей", "required": False, 'input': False},
            {'label': 'land_square', 'type': 'integer', "title": "Площадь дома м2*", "placeholder": "", "required": True, 'input': True}, 
            {'label': 'living_square', 'type': 'integer', "title": "жилая", "placeholder": "", "required": False, 'input': True},
            {'label': 'kitchen_square', 'type': 'integer', "title": "кухня", "placeholder": "", "required": False, 'input': True},
            {'label': 'heating', 'type': 'integer',  "title": "Отопление*", "placeholder": "Отопление", "required": False, 'input': False},
            {'label': 'phone_info', 'type': 'integer', "title": "Телефон", "placeholder": "", 'required': False, "input": False},
            {'label': 'internet', 'type': 'integer', "title": "Интернет", "placeholder": "", 'required': False, "input": False},
            {'label': 'furniture', 'type': 'integer', "title": "Мебель", "placeholder": "", 'required': False, "input": False},
            {'label': 'safety', 'type': 'integer', "title": "Безопасность", "placeholder": "", 'required': False, "input": False},
            {'label': 'documents', 'type': 'integer', "title": "Правоустанавливающие документы", "placeholder": "", 'required': True, "input": False},
            {'label': 'room_option', 'type': 'integer', "title": "Разное", "placeholder": "", 'required': False, "input": False},
            {'label': 'description', 'type': 'string', "title": "Описание", "placeholder": "Опишите, почему ваш объект стоит выбрать...", 'required': True, "input": True},
        ],
        '5': [
            {'label': 'square', 'type': 'integer', "title": "Площадь участка, соток*", "placeholder": "", "required": False, 'input': True},
            {'label': 'land_location', 'type': 'integer', "title": "Местоположение", "placeholder": "", 'required': False, "input": False},
            {'label': 'land_amenities', 'type': 'integer', "title": "Комуникации", "placeholder": "", 'required': False, "input": False},
            {'label': 'land_options', 'type': 'integer', "title": "Разное", "placeholder": "", 'required': False, "input": False},
            {'label': 'documents', 'type': 'integer', "title": "Правоустанавливающие документы", "placeholder": "", 'required': True, "input": False},
            {'label': 'description', 'type': 'string', "title": "Описание", "placeholder": "Опишите, почему ваш объект стоит выбрать...", 'required': True, "input": True},
        ],
        '6': [
            {'label': 'rooms', 'type': 'integer', "title": "Количество комнат", "placeholder": "Количество комнат*", "required": True, 'input': False},
            {'label': 'material', 'type': 'integer', "title": "Тип строения*", "placeholder": "Тип строения", "required": False, 'input': False},
            {'label': 'land_square', 'type': 'integer', "title": "Площадь дачи м2*", "placeholder": "", "required": True, 'input': True}, 
            {'label': 'square', 'type': 'integer', "title": "Площадь участка, соток*", "placeholder": "", "required": False, 'input': True},
            {'label': 'heating', 'type': 'integer',  "title": "Отопление*", "placeholder": "Отопление", "required": False, 'input': False},
            {'label': 'condition', 'type': 'integer', "title": "Состояние*", "placeholder": "Состояние", "required": True, 'input': False},
            {'label': 'phone_info', 'type': 'integer', "title": "Телефон", "placeholder": "", 'required': False, "input": False},
            {'label': 'canalization', 'type': 'integer', "title": "Канализация", "placeholder": "", 'required': False, "input": False},
            {'label': 'gas', 'type': 'integer', "title": "Газ", "placeholder": "", 'required': False, "input": False},
            {'label': 'water', 'type': 'integer', "title": "Питьевая вода", "placeholder": "", 'required': False, "input": False},
            {'label': 'furniture', 'type': 'integer', "title": "Мебель", "placeholder": "", 'required': False, "input": False},
            {'label': 'electricity', 'type': 'integer', "title": "Пол", "placeholder": "", 'required': False, "input": False},
            {'label': 'furniture', 'type': 'integer', "title": "Мебель", "placeholder": "", 'required': False, "input": False},
            {'label': 'safety', 'type': 'integer', "title": "Безопасность", "placeholder": "", 'required': False, "input": False},
            {'label': 'documents', 'type': 'integer', "title": "Правоустанавливающие документы", "placeholder": "", 'required': True, "input": False},
            {'label': 'options', 'type': 'integer', "title": "Разное", "placeholder": "", 'required': False, "input": False},
            {'label': 'description', 'type': 'string', "title": "Описание", "placeholder": "Опишите, почему ваш объект стоит выбрать...", 'required': True, "input": True},
        ],
        '7': [
            {'label': 'parking_type', 'type': 'integer', "title": "Тип объекта", "placeholder": "Тип объекта", "required": False, 'input': False},
            {'label': 'documents', 'type': 'integer', "title": "Правоустанавливающие документы", "placeholder": "", 'required': True, "input": False},
            {'label': 'description', 'type': 'string', "title": "Описание", "placeholder": "Опишите, почему ваш объект стоит выбрать...", 'required': True, "input": True},
        ],
    }
}
# #         'land': [
# #             {'name': 'land_area', 'type': 'float'},
# #             {'name': 'price', 'type': 'float'},
# #             {'name': 'currency', 'type': 'string', 'choices': [currency[0] for currency in choices.CURRENCY_TYPE]},
# #         ],
# #         'summer_house': [
# #             {'name': 'room_count', 'type': 'string', 'choices': [room[0] for room in choices.ROOM_COUNT_OPTIONS]},
# #             {'name': 'land_area', 'type': 'float'},
# #             {'name': 'price', 'type': 'float'},
# #             {'name': 'currency', 'type': 'string', 'choices': [currency[0] for currency in choices.CURRENCY_TYPE]},
# #         ],
# #         'parking_garage': [
# #             {'name': 'price', 'type': 'float'},
# #             {'name': 'currency', 'type': 'string', 'choices': [currency[0] for currency in choices.CURRENCY_TYPE]},
# #             {'name': 'parking', 'type': 'string', 'choices': [choice[0] for choice in choices.PARKING_CHOICES]},
# #         ],
# #     },
# #     'sell': {
# #         'house': [
# #             {'name': 'room_count', 'type': 'string', 'choices': [room[0] for room in choices.ROOM_COUNT_OPTIONS]},
# #             {'name': 'type_building', 'type': 'string', 'choices': [building[0] for building in choices.BUILDING_TYPE_CHOICES]},
# #             {'name': 'land_area', 'type': 'float'},
# #             {'name': 'price', 'type': 'float'},
# #             {'name': 'currency', 'type': 'string', 'choices': [currency[0] for currency in choices.CURRENCY_TYPE]},
# #         ],
# #         # Добавьте аналогичные параметры для других типов недвижимости
# #     }
# # }
