# Generated by Django 5.1.1 on 2024-11-08 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_remove_phones_phone_phones_phones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='house.property'),
        ),
    ]
