# Generated by Django 5.1.1 on 2024-11-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_alter_phones_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
