# Generated by Django 5.1.1 on 2024-10-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type_property',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='type_deal',
            new_name='type_id',
        ),
    ]
