# Generated by Django 5.1.1 on 2024-10-15 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='eni_code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', code='invalid_eni', message='The UNI code must consist of 10 digits ***')], verbose_name='Код ЕНИ'),
        ),
    ]
