# Generated by Django 5.1.1 on 2024-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_rename_type_property_property_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=16, null=True, verbose_name='Второй Номер телефона пользователя'),
        ),
    ]
