# Generated by Django 5.1.1 on 2024-09-24 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_remove_property_slug_property_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактные информации'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_phone', to=settings.AUTH_USER_MODEL, verbose_name='Номер телефона пользователя'),
            preserve_default=False,
        ),
    ]
