# Generated by Django 5.1.1 on 2024-11-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_phones_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingprice',
            old_name='property',
            new_name='building',
        ),
    ]
