# Generated by Django 5.1.1 on 2024-10-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='admin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='iso2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
