# Generated by Django 5.1.1 on 2024-10-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_property_eni_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ceiling_height',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Высота потолков'),
        ),
    ]
