# Generated by Django 5.1.1 on 2024-10-15 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_property_ceiling_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='eni_code',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', code='invalid_eni', message='The cadastral number must consist of exactly 14 digits. ***')], verbose_name='Код ЕНИ'),
        ),
    ]
