# Generated by Django 5.1.1 on 2024-11-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_rename_property_buildingprice_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingprice',
            name='m2_price',
        ),
    ]
