# Generated by Django 5.1.1 on 2024-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_location_admin_name_alter_location_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='population',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
