# Generated by Django 5.1.1 on 2024-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_property_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Второй Номер телефона пользователя'),
        ),
    ]
