# Generated by Django 5.1.1 on 2024-11-08 17:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_remove_buildingprice_m2_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phones',
            name='phone',
        ),
        migrations.AddField(
            model_name='phones',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='phones',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.property'),
        ),
    ]
