# Generated by Django 5.1.1 on 2024-10-30 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_alter_property_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('m2_price', models.PositiveIntegerField(verbose_name='цена за метр')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='house.property')),
            ],
        ),
    ]
