# Generated by Django 5.1.1 on 2024-10-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_remove_property_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ad_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Ad Color'),
        ),
        migrations.AddField(
            model_name='property',
            name='ad_dark_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Ad Dark Color'),
        ),
        migrations.AddField(
            model_name='property',
            name='autoup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Auto UP Time'),
        ),
        migrations.AddField(
            model_name='property',
            name='autoup_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Auto UP Until'),
        ),
        migrations.AddField(
            model_name='property',
            name='colored_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Colored Until'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured',
            field=models.BooleanField(blank=True, null=True, verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_autoup',
            field=models.BooleanField(default=False, verbose_name='Is Auto UP'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Is Premium'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Is Top'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Is Urgent'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Is VIP'),
        ),
        migrations.AddField(
            model_name='property',
            name='premium_dark_gradient',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Premium Dark Gradient'),
        ),
        migrations.AddField(
            model_name='property',
            name='premium_gradient',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Premium Gradient'),
        ),
        migrations.AddField(
            model_name='property',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium Until'),
        ),
        migrations.AddField(
            model_name='property',
            name='topped_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Topped Until'),
        ),
        migrations.AddField(
            model_name='property',
            name='urgent_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Urgent Until'),
        ),
        migrations.AddField(
            model_name='property',
            name='vipped_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vipped Until'),
        ),
    ]
