# Generated by Django 5.1.1 on 2024-10-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_property_ad_color_property_ad_dark_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='land_square',
            field=models.IntegerField(blank=True, null=True, verbose_name='общая Площадь'),
        ),
    ]
