# Generated by Django 5.1.1 on 2024-09-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_alter_property_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
