# Generated by Django 5.1.1 on 2024-09-27 18:46

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='property',
            name='advertiser_type',
            field=models.CharField(choices=[('proprietor', 'Собственник'), ('Agent', 'Агент')], default=1, max_length=50, verbose_name='От чьего имени подается объявление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Второй Номер телефона пользователя'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pictures',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='house/user/pictures/list/'),
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
