# Generated by Django 5.1.1 on 2024-10-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_alter_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='options',
        ),
        migrations.AddField(
            model_name='property',
            name='options',
            field=models.ManyToManyField(blank=True, to='house.options', verbose_name='опция'),
        ),
    ]
