# Generated by Django 5.1.1 on 2024-10-31 18:53

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_remove_property_options_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pictures',
            field=versatileimagefield.fields.VersatileImageField(upload_to='house/pictures/list/'),
        ),
    ]
