# Generated by Django 5.1.1 on 2024-09-28 18:17

import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_remove_property_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
