# Generated by Django 5.1.1 on 2024-09-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_alter_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='house_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
