# Generated by Django 5.1.1 on 2024-10-31 18:53

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_alter_pictures_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pictures',
            field=versatileimagefield.fields.VersatileImageField(upload_to='house/'),
        ),
    ]
