# Generated by Django 5.1.1 on 2024-10-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_alter_pictures_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cadastre_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Код ЕНИ'),
        ),
    ]
