# Generated by Django 5.1.1 on 2024-11-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_alter_property_cadastre_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
