# Generated by Django 5.1.1 on 2024-09-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_property_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
