# Generated by Django 5.1.1 on 2024-09-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_alter_property_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
