# Generated by Django 5.1.1 on 2024-11-01 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_alter_property_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residentialcategory',
            old_name='building',
            new_name='material_id',
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='district_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.district'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='microdistrict_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.microdistrict'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.region'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='town_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.town'),
        ),
    ]
