# Generated by Django 5.1.1 on 2024-09-30 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_light', models.BooleanField(blank=True, default=False, null=True, verbose_name='Свет')),
                ('has_gas', models.BooleanField(blank=True, default=False, null=True, verbose_name='Газ')),
                ('has_internet', models.BooleanField(blank=True, default=False, null=True, verbose_name='Интернет')),
                ('has_heating', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отопление')),
                ('has_water', models.BooleanField(blank=True, default=False, null=True, verbose_name='Вода')),
                ('has_phone', models.BooleanField(blank=True, default=False, null=True, verbose_name='Телефон')),
                ('has_sewage', models.BooleanField(blank=True, default=False, null=True, verbose_name='Канализация')),
            ],
            options={
                'verbose_name': 'Коммуникации',
                'verbose_name_plural': 'Коммуникации',
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='house_area',
        ),
        migrations.AddField(
            model_name='property',
            name='balkony',
            field=models.CharField(blank=True, choices=[('Balcony', 'Балкон'), ('Glazed balcony', 'Застекленный балкон'), ('Loggia', 'Лоджия'), ('No balcony', 'Нет')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('Separate', 'Раздельный'), ('Combined', 'Совмещенный'), ('2 or more bathrooms', '2 с/у и более'), ('No bathroom', 'Нет')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='disposition_object',
            field=models.CharField(blank=True, choices=[('in_city', 'В городе'), ('along_road', 'Вдоль трассы'), ('in_hills', 'В предгорьях'), ('in_suburbs', 'В пригороде'), ('near_water', 'Возле водоема'), ('in_summer_cottage_area', 'В дачном массиве')], max_length=100, null=True, verbose_name='Расположение обьекта'),
        ),
        migrations.AddField(
            model_name='property',
            name='drinking_water',
            field=models.CharField(blank=True, choices=[('central_water_supply', 'Центральное водоснабжение'), ('possible_connection', 'Возможно подведение'), ('well', 'Скважина'), ('no', 'Нет')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity',
            field=models.CharField(blank=True, choices=[('yes', 'Есть'), ('possible_connection', 'Возможно подведение'), ('no', 'Нет')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, choices=[('Linoleum', 'Линолеум'), ('Parquet', 'Паркет'), ('Laminate', 'Ламинат'), ('Wood', 'Дерево'), ('Carpet', 'Ковролин'), ('Tile', 'Плитка'), ('Cork flooring', 'Пробковое')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='front_door',
            field=models.CharField(blank=True, choices=[('Wooden', 'Деревянная'), ('Metal', 'Металлическая'), ('Armored', 'Бронированная'), ('No door', 'Нет')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furniture',
            field=models.CharField(blank=True, choices=[('Fully furnished', 'Полностью меблирована'), ('Partially furnished', 'Частично меблирована'), ('Unfurnished', 'Пустая')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gas',
            field=models.CharField(blank=True, choices=[('Main pipeline', 'Магистральный'), ('Autonomous', 'Автономный'), ('Possible connection', 'Возможно подключение'), ('No gas', 'Нет')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='internet',
            field=models.CharField(blank=True, choices=[('ADSL', 'ADSL'), ('Wired', 'Проводной'), ('Fiber optic', 'Оптика')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Площадь учатска'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, choices=[('Parking', 'Паркинг'), ('Garage', 'Гараж'), ('Nearby guarded parking', 'Рядом охраняемая стоянка')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='phone_connection',
            field=models.CharField(blank=True, choices=[('Available', 'Есть'), ('Possible connection', 'Возможно подключение'), ('Not available', 'Нет')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sewage',
            field=models.CharField(blank=True, choices=[('central', 'Центральная'), ('possible_connection', 'Возможно подведение'), ('septic', 'Септик'), ('no', 'Нет')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='property',
            name='room_count',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6 or more', '6 и более'), ('Open plan', 'Свободная планировка')], max_length=50, null=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='из всего этажей'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_building',
            field=models.CharField(blank=True, choices=[('Brick', 'Кирпичный'), ('Panel', 'Панельный'), ('Monolith', 'Монолитный')], max_length=50, null=True, verbose_name='Тип строения'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_condition',
            field=models.CharField(blank=True, choices=[('Under finishing', 'Под самоотделку'), ('Euro renovation', 'Евроремонт'), ('Good', 'Хорошее'), ('Average', 'Среднее'), ('Not finished', 'Не достроено')], max_length=50, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_series',
            field=models.CharField(blank=True, choices=[('102 series', '102 серия'), ('104 series', '104 серия'), ('Improved 104 series', '104 серия улучшенная'), ('105 series', '105 серия'), ('Improved 105 series', '105 серия улучшенная'), ('106 series', '106 серия'), ('Improved 106 series', '106 серия улучшенная'), ('Stalinka', 'Сталинка'), ('Khrushchevka', 'Хрущевка'), ('Individual layout', 'Индивид. планировка')], max_length=50, null=True, verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='property',
            name='communication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house.communication', verbose_name='Коммуникации'),
            preserve_default=False,
        ),
    ]
