# Generated by Django 5.1.1 on 2024-10-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_communication_remove_property_house_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='house.communication', verbose_name='Коммуникации'),
        ),
    ]
