# Generated by Django 5.1.1 on 2024-11-01 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_alter_residentialcategory_object_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='upped_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
