# Generated by Django 5.1.1 on 2024-11-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_property_upped_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
