# Generated by Django 5.1.1 on 2024-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_alter_property_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='has_gas',
            field=models.BooleanField(default=False, verbose_name='Газ'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='Отопление'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='has_internet',
            field=models.BooleanField(default=False, verbose_name='Интернет'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='has_light',
            field=models.BooleanField(default=False, verbose_name='Свет'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='has_phone',
            field=models.BooleanField(default=False, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='has_sewage',
            field=models.BooleanField(default=False, verbose_name='Канализация'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='has_water',
            field=models.BooleanField(default=False, verbose_name='Вода'),
        ),
    ]
