# Generated by Django 5.1.1 on 2024-10-02 09:13

import hashid_field.field
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0017_alter_communication_has_gas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pictures',
            field=versatileimagefield.fields.VersatileImageField(upload_to='house/user/pictures/list/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=25, prefix='', primary_key=True, serialize=False),
        ),
    ]
