# Generated by Django 5.1.1 on 2024-10-06 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0018_alter_pictures_pictures_alter_property_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentialcategory',
            options={'ordering': ['id'], 'verbose_name': 'Жилой комплекс', 'verbose_name_plural': 'Жилой комплекс'},
        ),
        migrations.RemoveField(
            model_name='residentialcategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='residentialcategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='residentialcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='residentialcategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='residentialcategory',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='property',
            name='ceiling_height',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='ceiling_height',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house.location', verbose_name='Расположение обьекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='object_state',
            field=models.CharField(choices=[('scheduled', 'запланирован'), ('under construction', 'строится'), ('finalized', 'завершен'), ('commissioned', 'сдан в эксплуатацию'), ('frozen', 'заморожен')], default=1, max_length=50, verbose_name='Состояние обьекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='type_building',
            field=models.CharField(blank=True, choices=[('Brick', 'Кирпичный'), ('Panel', 'Панельный'), ('Monolith', 'Монолитный')], max_length=50, null=True, verbose_name='Тип строения'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='type_heating',
            field=models.CharField(blank=True, choices=[('Central', 'Центральное'), ('Gas', 'На газе'), ('Electric', 'Электрическое'), ('Mixed', 'Смешанное'), ('Solid fuel', 'На твердом топливе'), ('Liquid fuel', 'На жидком топливе'), ('No heating', 'Без отопления'), ('Autonomous', 'Автономное')], max_length=50, null=True, verbose_name='Тип отопления'),
        ),
    ]
