# Generated by Django 5.1.1 on 2024-10-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0019_alter_residentialcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialcategory',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Высота потолков'),
        ),
    ]
