# Generated by Django 5.1.1 on 2024-10-06 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0020_alter_residentialcategory_ceiling_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcategory',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата сдачи'),
            preserve_default=False,
        ),
    ]
