# Generated by Django 5.1.1 on 2024-10-06 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0021_residentialcategory_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcategory',
            name='about_complex',
            field=models.TextField(blank=True, null=True, verbose_name='Об объекте'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='housing_class',
            field=models.CharField(choices=[('Brick', 'Кирпичный'), ('Panel', 'Панельный'), ('Monolith', 'Монолитный')], default='premuim', max_length=50, verbose_name='Тип класса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='storey',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Этажность'),
            preserve_default=False,
        ),
    ]
