# Generated by Django 5.1.1 on 2024-10-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0022_residentialcategory_about_complex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialcategory',
            name='housing_class',
            field=models.CharField(choices=[('econom', 'эконом'), ('comfort', 'комфорт'), ('business', 'бизнес'), ('premuim', 'премуим')], max_length=50, verbose_name='Тип класса'),
        ),
    ]
