# Generated by Django 5.1.1 on 2024-10-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0024_property_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='active_post',
            field=models.BooleanField(default=True, verbose_name='Активный пост'),
        ),
    ]
