# Generated by Django 5.1.1 on 2024-10-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0026_property_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcategory',
            name='lat',
            field=models.FloatField(default=42.8781737392183),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='lon',
            field=models.FloatField(default=74.59331083679504),
            preserve_default=False,
        ),
    ]
