# Generated by Django 5.1.1 on 2024-10-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0027_residentialcategory_lat_residentialcategory_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialcategory',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
