# Generated by Django 5.1.1 on 2024-10-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0028_alter_residentialcategory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
