# Generated by Django 5.1.1 on 2024-10-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0029_property_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='media',
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
