# Generated by Django 5.1.1 on 2024-10-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='object_id',
            field=models.CharField(max_length=200),
        ),
    ]
